### ISSUE TITLE
drop-in 3DS redirect uses WebView 

### ISSUE THREAD

**Issue by Binitronics** [Adyen/adyen-web#1008]
**Describe the bug**
We uses hybrid framework (ionic) to develop our Mobile App. We uses a drop-in approach to show available payment methods. When we choose 3DS1 card for our payment, an authentication page is opened in the WebView. This causes the app to freeze even sometimes to crash. 

**Expected behavior**
We expect the authentication page to be opened in a new window (browser). The droin.handleaction() method should not use the WebView to show the authentication page. PayPal is a good example for this as the authentication page is opened in a new browser. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy-S10
 - OS: Android 11
 - Browser WebView
 - Version SDK 3.23

**Additional context**

**Comment by marcperez** [comment]
Hi @Binitronics,

Thanks for reaching. The `handleAction` method of the Drop-in component will redirect using a `<form>` POST in the case of 3DS1, or a regular `window.location.assign` for other GET redirects. The choice of a WebView or the browser to handle those, is something handled by Ionic, in this case. I'd advise checking if Ionic has any configuration that gives you control over how to handle redirects.
Otherwise, actions can also be handled manually. You could manually handle all `redirect` type actions and redirect the shopper differently, if that works better in this specific use case. See [Handling Redirects in our docs](https://docs.adyen.com/online-payments/api-only/handling-redirects) for more details.

I'll close this issue, but please feel free to reopen if you think this is still relevant. Hope this helps!
