### ISSUE TITLE
How to enable the error state on input to add custom logic

### ISSUE THREAD

**Issue by fernandoamz** [Adyen/adyen-web#1230]
Hello everyone, I have a question/suggestion, I hope you can help me.

**Is your feature request related to a problem? Please describe.**
I want to enable the error status from the input if I require it, I am searching for a way to change the error status from an input.

**Describe the solution you'd like**
I mean something like this

```
  dropin.setState({
    ...dropin.state,
    errors: {
     ...dropin.errors,
     cardNumberMaskValid: false,
    }
  })
```
in order to be capable to add my own custom logic.

**Describe alternatives you've considered**
I tried many ways to do this but I couldn't enable the error state on the input.

I appreciate your help, thanks so much for reading me.

**Comment by marcperez** [comment]
Hi @fernandoamz,

Thank you for reaching out. Currently we have a way to display all the validation errors (on current invalid fields):

```js
dropin.showValidation();
```

We don't have any functionality to "force" a validation state on a component, though. Would `showValidation()` help you in this case? Otherwise, can you tell us a bit more about the use case where you'd like to override this validation states?

**Comment by ribeiroguilherme** [comment]
This issue seems to be stale, therefore I am closing it for now. Feel free to reach out if you have problems using the library.

**Comment by aaronguernsey** [comment]
@ribeiroguilherme and @marcperez 

What if the field is invalid after submission? (Using the session checkout with additional methods flow.)

For example, a user tries to submit a credit card with an invalid CVC field. After a payment has been submitted, an error is sent back from the server with the Refusal code: `24`. 

Questions:
- How would you update the drop-in form in the `onSubmit(state, component)` event to display that the CVC field is invalid and the user needs to input a new security code?
  - `component.showValidation()` will not display an error state because the CVC field is filled in and valid in the form

- Is this an anti-pattern to the statement: `Do not expose the details of specific refusal reasons to shoppers.`?

**Comment by sponglord** [comment]
@aaronguernsey - As a rule we advise merchants to be careful with exposing refusal reasons, as malicious shoppers can use it for card testing or other acts. In general, we advice merchants to only show generic refusal reasons.

For this reason we don't support the kind of flow you are asking about: try to pay, if it fails - get told why and try again within the same payment method.
Instead we opt for the flow: try to pay, if it fails, present a clean Dropin/component to the shopper
