### ISSUE TITLE
Add support for RTL attribute to AdyenCheckout Configuration

### ISSUE THREAD

**Issue by krishnakumar-tw** [Adyen/adyen-web#1264]
**Is your feature request related to a problem? Please describe.**
We are using Custom Card Integration of Adyen in our web application(VueJS) and trying to include Arabic language support. Although we are able to set translations properly, we couldn't enable "right-to-left" behaviour on the field Iframe component. 

**Describe the solution you'd like**
Similar to *locale* attribute we can set in configuration to AdyenCheckout instance. We would like to see a new attribute may be called *enableRTL*/*rtl*/*direction* etc.

**Describe alternatives you've considered**
- We have tried to set dir attribute on the "encryptedCardNumber" field using *document.getElementById*, it returns null value. 
- We have tried setting *dir: "rtl"* to parent of the iframe which did not work as well

Right now, we are out of options and do not see any other alternatives.

**Additional context**
Adyen Web version: 4.7.0

**Comment by marcperez** [comment]
Hi @krishnakumar-tw,

Thanks for reaching out. In our research, card numbers are entered in the LTR direction even on RTL locales, that's why we don't have any specific setting for the custom card component. We support RTL locales on all other relevant fields of other components (by using the `dir` attribute on a parent element). Hope this helps!

**Comment by krishnakumar-tw** [comment]
Hi @marcperez , thanks for quick response. Few follow up questions for better understanding 

1. Does this understanding apply to expiryDate and CVV fields as well apart from card number field?
2. When you say other components, do you mean other implementations of card like drop-in/component approaches. Or do you mean, other payment integration components?
3. In case we want to achieve this, is there any possibility with Custom Card Integration?

**Comment by marcperez** [comment]
Hi @krishnakumar-tw,

1. Yes, that applies to the three fields of the custom card component.
2. Correct, I mean other components of this library (except the card fields of the card component).
3. We're not planning on to adding support for this property on these fields since changing the direction of a card input is considered a bad user experience. An alternative could be changing the `text-align` to `right` (direction would stay the same but it would align with the rest of the fields).

Hope this helps!

**Comment by marcperez** [comment]
I'll be closing this ticket, but feel free to reopen it or contact our [support team](https://www.adyen.help/hc/en-us) if you have any further questions, thanks!
