### ISSUE TITLE
Angular + @adyen/adyen-web 5.2

### ISSUE THREAD

**Issue by Dashti81** [Adyen/adyen-web#1358]
Hi,

Is it possible to update this repo with the latest version of @adyen/adyen-web package?
https://github.com/adyen-examples/adyen-angular-online-payments

I'm looking for how to create checkout in typescript. Any example or suggestion is welcome.

thanks

**Comment by ribeiroguilherme** [comment]
Hi @Dashti81 ,

Thanks for reaching out. We are going to update our examples in the upcoming weeks with the latest `adyen-web` version. 

On this repository that you shared, you can find the creation of the Checkout in the [checkout.component.ts](https://github.com/adyen-examples/adyen-angular-online-payments/blob/master/checkout/src/app/components/checkout/checkout.component.ts) file.  It is using `adyen-web 4.5.0` in this sample.

In order to use the latest version of `adyen-web`, you need to instantiate `AdyenCheckout` asynchronously. More about it can be found [here](https://docs-admin.is.adyen.com/online-payments/release-notes#releaseNote=2021-10-06-web-componentsdrop-in-5.0.0). 

For this specific example, you can [instantiate AdyenCheckout](https://github.com/adyen-examples/adyen-angular-online-payments/blob/ceaaf7da995fb0811d4d8261ae7dfec70475fd98/checkout/src/app/components/checkout/checkout.component.ts#L102) asynchronously by doing: 

```javascript
AdyenCheckout(configuration)
    .then(checkout => {
        checkout.create(this.type).mount(this.hook.nativeElement);
    });
```

I hope it helps!
