### ISSUE TITLE
Web component: callback for loading error

### ISSUE THREAD

**Issue by JesusNaturitas** [Adyen/adyen-web#1369]
Hi.

I'm looking for a way to show an error message when card form fails to load on your side.

A onConfigFailure callback (opposite to existing onConfigSuccess callback) would do the trick. Is there any similar callback?

Thanks a lot!

**Comment by ribeiroguilherme** [comment]
Hi @JesusNaturitas ,

Do you mean the whole card form, or just the secured fields? Can you please clarify the scenario that you are trying to achieve?

It can help If you share a code snippet/screenshots of what is happening or what you expect to happen.

**Comment by Jazilch** [comment]
👋  I am also looking for something similar. I am using a custom card integration and I have seen a few times that it appears adyen.js loads successfully in the network tab but then an error occurs when configuring adyen. I had a har file sent to me from the customer and this is why I saw that the adyen script loaded correctly but the secured fields never configured and the customer wasn't able to use the form. 

I am using the `onConfigSuccess` callback to see when the payment form is correctly configured but it would be great if there was also a `onConfigFailure` callback so that when these issues occur I could get a better idea of the error to help out my customers. 

This issue has been very tricky to debug and I haven't been able to repro myself the extra error reporting would be helpful to see why the form didn't configure correctly.

**Comment by Jazilch** [comment]
@ribeiroguilherme Did you have any thoughts on my example above? Not sure if this gives you enough information about a use case for this callback

**Comment by sponglord** [comment]
I believe that this issue has been addressed with PR #1714
