### ISSUE TITLE
IE 11 credit card validation

### ISSUE THREAD

**Issue by tpatartmajeur** [Adyen/adyen-web#1401]
**Describe the bug**
Hi, I'm getting an error using @adyen/adyen-web 5.3.1 with credit card validation on IE11.

This is probably due to the use of Array.fill. 

![Adyen](https://user-images.githubusercontent.com/51753505/144612380-3cdda00e-f738-45ad-b112-ea81fe2d0a9c.png)

**Expected behavior**
The credit card should be valid

**Desktop (please complete the following information):**
Tested in Windows 10/IE11

**Comment by ribeiroguilherme** [comment]
Hi @tpatartmajeur 

Thanks for reaching out to us. We introduced `Array.fill` in our secured input fields in one of the recent releases, and indeed it is missing polyfill for IE11. The fix will be available early next year, as there are delays for the releases due to the time of the year.

As a workaround for that, I suggest to use the version 5.2.0 which isn't using `Array.fill`. I hope it helps!
