### ISSUE TITLE
Adyen component can not work in IE11 when runing adyen-react-online-payments Demo

### ISSUE THREAD

**Issue by 273853065** [Adyen/adyen-web#1403]
**Describe the bug**
Hi team, 
I was trying to run the Adyen react demo in my local environment, the repo link is [adyen-react-online-payments](https://github.com/adyen-examples/adyen-react-online-payments)
When I npm run server in my local, and run it in the IE11, the whole page will not be shown.
And in the browser F12, it will shown the error as the screenshot below.
**Does Adyen dependency not support IE11?
Could you please help to check? Thank you from the bottom of my heart.**
![image](https://user-images.githubusercontent.com/10972062/144783088-97016e81-a69f-413e-82fe-b8638c39d5d9.png)

**To Reproduce**
1. git clone [git@github.com:adyen-examples/adyen-react-online-payments.git](git@github.com:adyen-examples/adyen-react-online-payments.git)
2. npm install
3. npm run server
4. open the url([http://localhost:8080](http://localhost:8080)) in IE11

**Expected behavior**
It should be normal same as Chrome, I post a screenshot of Chrome as below.
![image](https://user-images.githubusercontent.com/10972062/144783434-7196bf3e-3ea1-4403-89cc-c8f29f0693e8.png)

**Screenshots**
IE error
![image](https://user-images.githubusercontent.com/10972062/144783088-97016e81-a69f-413e-82fe-b8638c39d5d9.png)
Chrome browser is normal
![image](https://user-images.githubusercontent.com/10972062/144783434-7196bf3e-3ea1-4403-89cc-c8f29f0693e8.png)

**Desktop (please complete the following information):**
 - OS: [Window10]
 - Browser [IE]
 - Version [IE11]

**Comment by ribeiroguilherme** [comment]
Hey @273853065 ,

The problem is that the demo app isn't applying polyfiils on the codebase, and to run on IE11 that is a requirement. I will create a task to fix that, thanks for sharing with us.

For now, what you can do is to add  the polyfills by yourself. I believe that adding [react-app-polyfill](https://github.com/facebook/create-react-app/tree/main/packages/react-app-polyfill) library to the project will fix the problem. I hope it helps!
