### ISSUE TITLE
Adyen doesn't provide minified resources (including java script and stylesheets) , also the resources are fetched through HTTP 1.1 protocol

### ISSUE THREAD

**Issue by karanbaneshi99** [Adyen/adyen-web#1405]
We have integrated Adyen JS SDK for Ideal payment method using the below scripts and stylesheets

- https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/4.5.0/adyen.js
- https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/4.5.0/adyen.css

In order to improve the performance of our web-app. Can you please provide us with the below two optimizations

- Provide us with the minified versions of javascript and stylesheet resources
- Move the protocol with these resources from HTTP 1.1 to HTTP 2

As of now there is no such provision on the web-component integration part (although HTTP 2 is available on NPM , but due to some constraints we can't use NPM in our web-app) , Please provide us with both of these optimizations

Thanks
Karan

**Comment by ribeiroguilherme** [comment]
Hi @karanbaneshi99 ,

Thanks for reaching out to us. The javascript code is already minified, although the CSS there for this specific version isn't, which is quite weird. Regardless of that, if that is a big deal for you, you can simply use a newer version which has the minified CSS version. I am afraid that changing it won't bring much benefits though, since the minified version is 10kB , and the non-minified is 11kB.

About the protocol, we are working to support HTTP2, but there is no specific estimative when it will be done and released. The workaround for now is to serve the assets by your own server, so you have full control over them.

Hi @karanbaneshi99 ,

Thanks for reaching out to us. The javascript code is already minified, although the CSS there for this specific version isn't, which is quite weird. Regardless of that, if that is a big deal for you, you can simply use a newer version which has the minified CSS version. I am afraid that changing it won't bring much benefits though, since the minified version is 10kB , and the non-minified is 11kB.

About the protocol, we are working to support HTTP2, but there is no specific estimative when it will be done. The workaround for now is to serve the assets by your own server, so you have full control over them.

I hope this sets your expectations about these topics!
