### ISSUE TITLE
Simplified payment flow for Amazon Pay integration

### ISSUE THREAD

**Issue by ahimik** [Adyen/adyen-web#1551]
**Is your feature request related to a problem? Please describe.**

`adyen-web` starting from v `5.0.0+` implements simplified payment flow using sessions mechanism,
however `Amazon Pay` integration doesn't support new flow and requires separate drop in configuration, action bindings and manual `/payments` request execution and action processing.

**Describe the solution you'd like**

Drop-in should handle `Amazon Pay` payment workflow and make `/payments`, `payments/details` requests by itself within opened payment `session` as it does for cards or PayPal or Apple Pay payments. It should also process redirects automatically in the same way as it does for other payment methods starting from v `5.0.0` .

**Comment by m1aw** [comment]
Hey Alex,

Sorry I forgot to reach out to you on the other thread. Unfortunately by design Amazon Pay works in quite a different way then rest of payment methods since it requires redirect back to the component/dropin page. 
Currently we don't have plans for this feature, I will forward this internally to see if there is desire from a product level to follow up with this.
