### ISSUE TITLE
Apple Pay visible when allowedPaymentMethods is set only to "scheme"

### ISSUE THREAD

**Issue by nahojd** [Adyen/adyen-web#1640]
**Describe the bug**
When using the web drop-in component, and creating a new session where allowedPaymentMethods is set to ["scheme"] (in order to only show the card payment window), the payment component shows both Apple Pay and Card options.

**To Reproduce**
1. Activate Apple Pay
2. Create a new session with allowedPaymentMethods = ["scheme"]
3. Create a new AdyenCheckout for that session

**Expected behavior**
Only the card payment option should be visible.

**Browser and OS**
Safari on Mac or iOS, Apple Pay is not visible on other browsers or platforms.

**Additional context**
Apple pay configuration is specified in the paymentMethodsConfiguration, but so is PayPal, and that doesn't show up.

**Comment by ribeiroguilherme** [comment]
@nahojd I investigated internally and indeed returning ApplePay is not the intentional behavior when setting the allowPaymentMethods to 'scheme'.  We created a ticket to resolve this on the new API version.

For now, I suggest to follow the approach that I mentioned above - it should do the trick.

I am going to close this ticket as it is not related to the Web SDK per se, but feel free to reach out if you need any other help. And thanks again for reporting it. Cheers!

**Comment by nahojd** [comment]
@ribeiroguilherme Thanks! We have worked around it with the suggested solution of blocking apple pay when scheme is selected, so it's working for us in the mean time.
