### ISSUE TITLE
[dropin] onError not triggered when pay with credit card

### ISSUE THREAD

**Issue by robyhuzwandar** [Adyen/adyen-web#1815]
onError from the checkout config doesn't trigger onError only on the credit card. but it triggered onCompleted even my pay action is error 

```js

 const adyenUIConfig = {
          ...

          onPaymentCompleted: (result: any, component: any) => {
            console.info(result, component);  <----- but it triggered onCompleted instead of trigger on error
          },
          onError: (error: any, component: any) => {
            navigate(route('/error-page')); <---- not trigger on credit card
          },

          ...
        };

        const checkout = await AdyenCheckout(adyenUIConfig);

```

Based on the documentation credit card have owned [event](https://docs.adyen.com/payment-methods/cards/web-drop-in?tab=_code_payment_methods_code__2#events)

but where to put or call the events? the documentation does not explain clearly.
Could you show me an example of how to use the onError event for the credit card?

what do I want to solve? I want to add my own page error instead of using the error UI built-in

I want replace this Error component with my own error page
<img width="450" alt="image" src="https://user-images.githubusercontent.com/20414047/198543493-67ed6090-1b7c-4182-83df-b5eac1bda842.png">

**Comment by sponglord** [comment]
Hi @robyhuzwandar 
Since v5 of Adyen-web the `onError` event has become a [generic one](https://docs.adyen.com/online-payments/release-notes#releaseNote=2021-10-06-web-componentsdrop-in-5.0.0)

I'm getting our documentation team to update the link you refer to.

As far as getting credit card specific errors... what errors exactly are you trying to capture?
I'm presuming from your screenshot that these are failed payment errors rather than in-form, validation, errors?
Can you also tell me which integration you are using - the "Advanced flow" or "Sessions?

**Comment by ribeiroguilherme** [comment]
Closing this as the issue is stale. Feel free to reach out if the problem persists.
