### ISSUE TITLE
onCancel event not being fired for 3D Secure 2 web component

### ISSUE THREAD

**Issue by lluishi93** [Adyen/adyen-web#1839]
**Describe the bug**
When the "Cancel" button is clicked on the 3D Secure 2 web component, the onCancel event is not being fired.

**To Reproduce**
1. Instantiate a 3D Secure 2 component
2. Initialize the "onCancel" function the do something (console.log for instance)
3. Click "Cancel" when the 3DS2 component appears
4. Check that your console.log does not appear on the DevTools console

**Expected behavior**
The onCancel function should be called when the "Cancel" button is clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/14786440/201705719-b529e585-1149-47e3-91d7-35f44863fb1b.png)
![image](https://user-images.githubusercontent.com/14786440/201706009-bc2f6b28-5027-462c-b0c7-de816298bd1d.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Chrome
 - Version 107.0.5304.110

**Additional context**
We're using the "@adyen/adyen-web": "5.11.0" version

**Comment by sponglord** [comment]
Hi @lluishi93 - thanks for raising this!
Strictly speaking this isn't an issue with adyen-web.
The page you see here is a simulation of the kind of 3DS2 challenge page that the ACS/Issuer will present to a shopper. It is not something generated by adyen-web (we just create an iframe to hold this content, but have no control over what that content is)
I have alerted the team responsible for maintaining this test 3DS2 challenge page

**Comment by sponglord** [comment]
Hi @lluishi93 - thanks for raising this issue
Strictly speaking this isn't an issue with adyen-web.
The page you see here is a simulation of the kind of 3DS2 challenge page that the ACS/Issuer will present to a shopper. It is not something generated by adyen-web (we just create an iframe to hold this content, but have no control over what that content is). 
Because of this the `Cancel` button should not be equated with the `onCancel` callback - which, incidentally, is used by a couple of payment Methods (ApplePay, PayPal) but _not_ the credit card component. (I'm curious as to how you know this callback even exists...?)
Clicking on the `Cancel` button, however, does lead to a measurable result - cancelling is a legitimate user action in the 3DS2 flow and will lead to a call to any `onAdditionalDetails` handler that you have defined.
If this handler then makes the expected call to the `/payments/details` end point you will get a response with a `resultCode: "Refused"` and a `refusalReason: "3D Not Authenticated"`

**Comment by sponglord** [comment]
@lluishi93 

I would still like to know how you came to know about the `onCancel` handler? - since this has nothing to do with the credit card/3DS2 component and is not meant to be used in this context (for the reasons explained in my previous answer)

Also I have tested 4 scenarios now:
- card component
- dropin (sessions)
- dropin (manual/advanced flow)
- standalone 3DS2 component (`/payments` call made elsewhere, just use to Checkout to handle the `action` in the response i.e. `checkout.createFromAction(action).mount('#my-container');`)

All of them behave as expected:
> Clicking on the Cancel button, however, does lead to a measurable result - cancelling is a legitimate user action in the 3DS2 flow and will lead to a call to any `onAdditionalDetails handler` that you have defined.
If this handler then makes the expected call to the `/payments/details` end point you will get a response with a resultCode: "Refused" and a refusalReason: "3D Not Authenticated"

These tests were run using the latest version of adyen-web (`v5.29.0`) - maybe you need to upgrade?

Another point to note is that the page in question is just a simulated 3DS2 challenge page - not all "real world" challenges will necessarily have a cancel button - so you shouldn't be trying to directly capture this event.
