### ISSUE TITLE
Google pay error message on cancel is "[object Object]"

### ISSUE THREAD

**Issue by BackEndTea** [Adyen/adyen-web#1877]
**Describe the bug**
When canceling a google pay payment (closing the window for example). The error that gets sent to the `onError` function that was passed to the Checkout has the message `[object Object]`. The error name is also `ERROR` instead of `CANCEL` like with other payment methods

**To Reproduce**
1. Attempt payment with google pay
2. Cancel the payment
3. Check the onError callback

**Expected behavior**
I expected the `error.name` to be CANCEL, and to have a normal error message

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser firefox
 - Version 107

This has also been reproduced on a chromebook with google chrome, but i'm not sure about the exact version numbers there

**Comment by ribeiroguilherme** [comment]
Hey @BackEndTea ,

What version of the SDK are you using? When trying to reproduce the issue, I am getting the proper error message and not the `[object Object]` .  In my case, `error.message` has the value: 'AbortError: User closed the Payment Request UI.'

In regards of the error name - we are indeed passing `ERROR` and not `CANCEL`. We can't simply change it because this could potentially break other integrations. I also assume that, from the GooglePay SDK, all sorts of errors could be fired besides CANCEL, so that is why we are naming it as more generic `ERROR`.

**Comment by BackEndTea** [comment]
I have tracked it down to this line 

https://github.com/Adyen/adyen-web/blob/a39e82c31d8c836e8112ff2f5009032fea2d844a/packages/lib/src/components/GooglePay/GooglePay.tsx#L63

I added `console.log(e, e.toString())` to the minified code on my side and got this result.

This is with SDK version 5.30.1 (the latest at moment of writing this)

![image](https://user-images.githubusercontent.com/14289961/210215327-5e6847aa-8c77-4e25-92af-e1444a8dcb3f.png)

**Comment by BackEndTea** [comment]
Okay, i did some further digging.

On chrome the message comes through correct as `'AbortError: User closed the Payment Request UI.'` However, on both firefox 108, and safari 16.1, the message is `[object Object]`

**Comment by BackEndTea** [comment]
Thanks @ribeiroguilherme !
