### ISSUE TITLE
Is the Idempotency key not used on web components integration?

### ISSUE THREAD

**Issue by JulianaMota** [Adyen/adyen-web#2022]
We have been trying to add the idempotency key on our Adyen integration since we have some duplicate payments. However, by using the web component integration we are not able to send it on payments. Should that not be possible to add on the request below by Adyen?
https://github.com/Adyen/adyen-web/blob/99668f7dfb0670ef34ed0d2ea90247f166a0652b/packages/server/api/payments.js#L7

Thank you for the help

**Comment by sponglord** [comment]
@JulianaMota If it is related to a `/sessions implementation` - we do not support idempotency there.
I'm closing this issue because, strictly speaking, this question relates to our Checkout API rather than our components.

If you do have API related questions please reach out to our Tech support (https://help.adyen.com/contact) and they will channel the issue to the relevant team.
Thanks.

**Comment by JulianaMota** [comment]
Hi @sponglord 

Our question is not related to the use of the idempotency key specific to sessions/. Was more of a general question on component integration. We wanted to know if the idempotency key is used in components or if it will be enabled in the future
Thank you for the help.

Juliana
Unisport, Fullstack Developer
