### ISSUE TITLE
VUE Dropin closeActivePaymentMethod Stop working (CRITICAL)

### ISSUE THREAD

**Issue by EduardoMateos** [Adyen/adyen-web#2173]
**Describe the bug**
When using dropin and then using the "closeActivePaymentMethod" dropin stops working.

**To Reproduce**
Use this repository -> https://github.com/EduardoMateos/adyen-bug-close-active-method

replace in this file: https://github.com/EduardoMateos/adyen-bug-close-active-method/blob/master/src/App.vue 
"YOUR CLIENT KEY" -> your adyen test key "test_XXXXXX"

**Expected behavior**
closed the active payment method with "closeActivePaymentMethod" it should be possible to open the payment method again if the user clicks on it.

**video**
https://github.com/Adyen/adyen-web/assets/11529050/32dd5a9c-f40c-438e-a8f9-97bc7a81e410

**Desktop (please complete the following information):**
 - OS: iOS 16
 - Browser Chrome
 - Version last

**Comment by ribeiroguilherme** [comment]
Hi @EduardoMateos ,

The problems seems to happen because you are defining the `dropin` property inside the `data()` method, and doing that seems to cause conflict as the HTML element`ref` is named `dropin` and the Component being created is also named `dropin`. 

Removing the `dropin` definition from `data()` makes the code work.

This should be some sort of Vue / Vue3 limitation. I suggest you to name variables and references with different names, so it can avoid such clashes. You can also take a look into [adyen-vue-example](https://github.com/adyen-examples/adyen-vue-online-payments), it might help. Cheers

**Comment by EduardoMateos** [comment]
Hello good,

I've updated the example https://github.com/EduardoMateos/adyen-bug-close-active-method, now I use different variables and it still happens. can you check it on localhost?

thank you

**Comment by EduardoMateos** [comment]
Solved by adyen suport:
```

    const checkout = await AdyenCheckout(adyenConfig);
    const dropin = checkout
      .create("dropin", {
        showPaymentMethods: true,
      })
      .mount(this.$refs.dropin);


    const els = document.querySelectorAll(".close-adyen");
    console.log(els)
    els.forEach(function (el) {
      el.addEventListener('click', () => {
        console.log("CLICK")
        dropin.closeActivePaymentMethod()
      });
    });
```
