### ISSUE TITLE
Disabled cardholder name and zip preventing payments on iOS Safari

### ISSUE THREAD

**Issue by ollym** [Adyen/adyen-web#2274]
Test site:
https://cdn.checkout.ventrata.com/v3/staging/index.html

The video below will demonstrate the issue. You can create it using mac safari and enable responsive design mode (Develop > Enter Responsive Design Mode)

I included step by step through the checkout flow so you're able to get to the same page, make sure you click the "Waterpark" button on the test site, this is the only one where we have cardholder name and zip enabled.

The key element to look out for is that for some reason (and only on iOS Safari) when you finish entering the expiry date the cardholder name and zip inputs are automatically disabled (as I demonstrate using the elements inspector). I then manually remove this attribute to demonstrate it then works.

This is a serious production-level bug, we've had to disable cardholder name and zip code for now, but its exposing us to fraud. Please fix this ASAP. 

https://github.com/Adyen/adyen-web/assets/143771/83349ce5-0bf3-488c-9b37-6bcdc6c465fe

URL in case the video above doesn't load: https://share.cleanshot.com/zY8CxRY5

**Comment by m1aw** [comment]
Hello @ollym,

Thank you for providing the detailed issue with the video; it was very useful for reproduction purposes. Let me start by addressing that the behavior you described only occurs in the responsive test environment on MacOS Safari. If you test it on a physical iOS device, you won't encounter the same problem.

To resolve this peculiar behaviour, you can pass the property `disableIOSArrowKeys: false` in the Card component/Dropin configuration.

This option disables a feature that works around an iOS behaviour, which was causing the user's input to jump away from the card details form when using the navigation arrows. The issue arises because the inputs for the card details (securedFields) exist within an iframe, and iOS doesn't recognise them as the "next" input to navigate to.

My recommendation is to test this behaviour to see which option better suits your users.

**Comment by ollym** [comment]
@m1aw sorry that's not accurate. The issue is relayed to partial billing address. We since changed this to full on our test site but the video depicts partial where the issue still exists.

**Comment by ollym** [comment]
@m1aw Sorry this doesn't work on a live device even with full billing address. Video from my personal iphone attached. And you can recreate with the link sent in my original post too.

https://github.com/Adyen/adyen-web/assets/143771/b3d1a958-3d88-4607-8a2f-39e03241288a

**Comment by ollym** [comment]
After adding `disableIOSArrowKeys: false` it fixes the issue but i still think this should be resolved by default without a flag.

**Comment by sponglord** [comment]
@ollym - In the next major release (v6.x) we will make this `disableIOSArrowKeys: false` the default value.
