### ISSUE TITLE
Ability to cancel started Swish payments

### ISSUE THREAD

**Issue by jesperjohansson** [Adyen/adyen-web#2372]
**Is your feature request related to a problem? Please describe.**
When starting a Swish payment its impossible to cancel from the checkout, for example if you want to change method. You have to wait for the timer to run out or cancel from the Swish app.

**Describe the solution you'd like**
Show a cancel-button on the "scan QR" page which cancels the Swish payment and returns you to the payment method selection.

**Describe alternatives you've considered**
Showing a cancel button outside the drop-in which would re-mount it, but that would look ugly.

**Additional context**
v5.50.0
Using the drop-in implementation.

![Screenshot 2023-10-18 at 15 41 18](https://github.com/Adyen/adyen-web/assets/21033162/5a3c9976-9e02-478f-928f-924703869a1d)

**Comment by ribeiroguilherme** [comment]
Hi @jesperjohansson ,

This is actually by design, as we don't intend to support this feature on Drop-in.

What is recommended in this case is use the Components integration, and then add your own cancelation button to the UI when the QR code is displayed. When the shopper clicks on it, you reload the Checkout page starting the checkout flow again. 

I hope it is clear. Cheers!
