### ISSUE TITLE
3DS Verification Page Redirect

### ISSUE THREAD

**Issue by josh-meredith** [Adyen/adyen-web#2393]
**Describe the bug**

I'm experiencing an issue with the web drop-in where the 3DS verification will always redirect to an external URL. The data payload returned from our payments endpoint is always similar to the object below.

Is there any way to force this action to be handled within an iframe, as opposed to an actual redirect? If a redirect happens and the user is then returned to the checkout page, we're not able to handle the result appropriately.

```
{
  method: "GET"
  paymentData: "XXXX"
  paymentMethodType: "scheme"
  type: "redirect"
  url: "https://checkoutshopper-test.adyen.com/checkoutshopper/threeDS/redirect?XXX"
}
```

**Expected behavior**
Open 3DS challenge within an iframe, as opposed to redirect.

**Screenshots**

**Desktop:**
 - OS: OS X
 - Browser: Chrome
 - Version: 118.0.5993.117

**Comment by sponglord** [comment]
Hi @josh-meredith - there are many reasons why our backend system might choose to decide a 3DS2 payment should be done via a redirect rather than be handled within the adyen-web library itself.

From the frontend side of things the influence you can have over this decision making process depends on the version of `adyen-web` and the `API` version that you are using - so can you please tell us both these version numbers? Thanks

**Comment by josh-meredith** [comment]
Thanks for the response @sponglord. We're running the following versions:

**adyen-web:** 5.53.2
**adyen-python-api-library:** 3.0.0

**Comment by sponglord** [comment]
Hi @josh-meredith - so with your implementation, to try and force 3DS2 into a "native" rather than Redirect flow, I believe you need to add an `additionalData` object in the data that gets sent to the `/payments` endpoint:
```
additionalData: {
   allow3DS2: true
}
```
I don't know if this is something you have control over when using the adyen-python-api-library?

**Comment by sponglord** [comment]
@josh-meredith - I think this issue lies with the python library and you need to create an issue there: [https://github.com/Adyen/adyen-python-api-library](https://github.com/Adyen/adyen-python-api-library)
