### ISSUE TITLE
More flexibility for installmentOptionMonths 

### ISSUE THREAD

**Issue by y-a-v-a** [Adyen/adyen-web#2592]
**Is your feature request related to a problem? Please describe.**

The translation key `installmentOptionMonths` is hard coded to contain the word "months". Especially in the situation that we would want to offer later payment in 1 installment, it sounds a bit weird to communicate to the consumer that she has to pay within one month.

**Describe the solution you'd like**

We would kindly request to take into consideration a change of this label into "times" or a different common synonym or a way to supply the wording ourselves.

**Describe alternatives you've considered**

Adyen support has suggested us to download the prebuilt package and change the word "months" into "times" ourselves. We are reluctant to do so because this goes against our general software development perspectives and would create a divergence of your development cycle that might lead to more complexity and maintenance.

**Comment by longyulongyu** [comment]
Hi @y-a-v-a ,

Thanks for your feedback, the installment when displayed as `x months` actually means monthly installments for most of the cases, but I will bring this up internally if we need to introduce a new translation key in order to cover the scenario for non-monthly installments.

For a quick fix, the text displayed in each localization can be customized, allowing you to replace the default text with your own. In your case, if you want to change the `months` into `times`, you could feed your own translation strings into the checkout configuration, e.g:
```javascript
const checkout = await AdyenCheckout({
        translations: {
            'en-US': {
                installmentOptionMonths: '%{times} time(s)'
            }
            // translations for other locales
        },
        // the rest props
    });
```
Let us know if this quick fix works for you.

**Comment by y-a-v-a** [comment]
Hi @longyulongyu thank you for your reply! We're going to look into this!
