### ISSUE TITLE
Prevent CTRL+C and mask Credit Card input

### ISSUE THREAD

**Issue by belliAndrea** [Adyen/adyen-web#2641]
**Is your feature request related to a problem? Please describe.**
We would like to prevent our customer service not be able to use CTRL+C to copy the Credit Card number/cvc
after writing it.
Also we would like to be able to mask the credit card number with dots while they are filling it.
Es.:  **** **** 1....

**Describe the solution you'd like**
for CTRL+C an API function to control the DOM events for the input and prevent the default (couldn't find any)
for the Mask just an api to be able to set this type of input (sort of a password type)

**Describe alternatives you've considered**
I tried a workaround but seems like i'm not able to reach the input in the iframe (probably security reason, am i right?)

**Comment by sponglord** [comment]
Hi @belliAndrea. 
Thanks for reaching out. 
The issue of masking the credit card number is one has come up before but the answer then, as now, is that we consider it a very bad user experience. Masking a long, 16 -19 digit, number will leave the shopper unsure about the digits they have already input, they have no way to check they haven't made a mistake, and this will lead to errors and have a negative impact on conversion rates.
(And you are right, you can't make a workaround yourself because the input is in an iframe for security reasons)

Regarding preventing users from copying the credit card number - overriding such a fundamental, default, behaviour of the browser/device is not something that we want to spend time investigating
