### ISSUE TITLE
Cards - Submit errors (Web component)

### ISSUE THREAD

**Issue by NicholasAntidormi** [Adyen/adyen-web#2801]
**Is your feature request related to a problem? Please describe.**
I need to handle submissions errors (eg. resultCode "Refused", refusalReason "CVC Declined") with the credit cards web component. Currently if I submit a wrong card, the form is not editable anymore and the inputs does not seems to have error classes.

**Describe the solution you'd like**
With the onError hook add error classes to input, show an error message and let the user modify the values and resubmit.

**Describe alternatives you've considered**
I think I can handle the style by adding an outer class myself and I can show the error in a dom element below the card form. However I'm not sure about how to let the user edit the wrong values.

Maybe I missed something in the doc, any help would be really appreciated, thanks!
(I'm in test mode)

**Comment by ribeiroguilherme** [comment]
Hi @NicholasAntidormi ,

The fields do not contain any errors because they are actually valid fields. The problem here is that the payment part failed due to the a certain reason (wrong CVC for example).

[Here is a similar request related to yours, and our recommendation how to handle these scenarios.](https://github.com/Adyen/adyen-web/issues/1230#issuecomment-1989550230) Let me know if that is clear.
