### ISSUE TITLE
Show validation error for credit card fields when they are empty on blur.

### ISSUE THREAD

**Issue by swapnadavid** [Adyen/adyen-web#284]
**Is your feature request related to a problem? Please describe.**
I am using the card component integration. I need to be able to show validation error for a field when a field is empty on blur. 
The credit card fields currently get validated only on change. 

**Describe the solution you'd like**
When a field loses focus, if the field is empty I want the field validated and the validation error message displayed. 

**Describe alternatives you've considered**
Currently on blur I am checking if the field is invalid and if it is I am calling the showValidation() on the card component. For example if the field that has lost focus is the card number field, calling showValidation() marks the card number, expiry and CVV fields as invalid. I have also explored the state/component params on onBlur, onChange, onFocus to see if there is a way to validate a field on blur when it is empty. 

**Additional context**

**Comment by marcperez** [comment]
Hi @swapnadavid,

Thanks for your suggestion, we will discuss internally and come back to you as soon as we have an answer.

**Comment by marcperez** [comment]
Hi @swapnadavid,

Thanks again for opening this issue. After our internal discussion we've agreed this is not a behavior we'd like to change at this moment.

We always anticipate on user's intent. We want to provide the best feedback at the right moment. Therefore, we only provide feedback when users have entered data in the input field. Triggering validation errors/feedback for empty input fields could make the UI noisy and could be frustrating for users (because they could think they're doing something wrong).

If you'd still like to implement such validation behavior, I'd advise using our [custom card component](https://docs.adyen.com/payment-methods/cards/custom-card-integration), where you have full flexibility on how to display validation errors.

Hope this helps!

**Comment by robmonie** [comment]
Hi @marcperez - I realise this has just been closed but wanted to add a use-case for consideration or possible suggestion of alternative solution. We're using the Custom Card Integration approach.

Our form designs have a field border color change when a field is focused. From what i've been able to see, there is no control given over the style of the underlying fields provided in the iframe so we're mimicking that by wrapping each iframe in a div that has a border. We're able to change the color of this border when a field is focused via the `onFocus` callback but without an `onBlur` we're unable to revert this back to it unfocused color.

**Comment by nickcaballero** [comment]
@robmonie the onFocus event has a flag to indicate if it's focused or not.

**Comment by robmonie** [comment]
thanks @nickcaballero  - I hadn't noticed that behaviour.
