### ISSUE TITLE
Adyen Web drop-in V5 missing issuer in payment method details

### ISSUE THREAD

**Issue by JordiDekker** [Adyen/adyen-web#2872]
**Describe the bug**
Hi, I am using the Adyen Web Drop-in version `5.69.1`  for providing an easy payment method selection. When selecting iDEAL I don't have to select an issuer (as expected), but when proceeding an error occurred in the POST-call. 

**To Reproduce**
1. Go to drop-in component
2. Select iDEAL as payment method
3. Proceed
4. See error in console: `NETWORK_ERROR: Missing payment method details: issuer [This error message is only provided on TEST, this error will be a 500 Internal Error on LIVE.]`

**Expected behavior**
To be compliant with iDEAL 2.0 I expect to see no issuer selection. Selecting iDEAL and proceed in the widget should result in a valid redirect to the iDEAL portal.

**Screenshots**
![Scherm­afbeelding 2024-09-25 om 11 08 54](https://github.com/user-attachments/assets/56df37a1-2fca-4c2d-8291-22d59c47b044)

**Comment by camil-adyen** [comment]
Hey @JordiDekker, due to the [new iDEAL 2.0](https://docs.adyen.com/payment-methods/ideal/ios-drop-in/#test-and-go-live) flow some changes were made to your payment methods setup in the Customer Area. Please enable the new ideal payment method confirgured to your test account and disable the old one to get the correct API response.

<img width="825" alt="367221043-96447ae4-1a33-420f-a0b0-c4079e89ab27" src="https://github.com/user-attachments/assets/7bb8ee1d-f587-40e3-bc11-7a8d46ca20cb">

**Comment by JordiDekker** [comment]
Hey @camil-adyen , thanks for your fast reply!
I found the payment methods configuration in the customer area, but it had iDEAL enabled.

Just to be sure, would you expect another iDEAL to be shown and configured here?
![Scherm­afbeelding 2024-09-25 om 12 28 18](https://github.com/user-attachments/assets/ea4c7822-a54d-42e5-ae29-837eb4cff987)

**Comment by camil-adyen** [comment]
Hey @JordiDekker, please look for iDEAL in the payment methods overview page in the CA. There should be multiple entries for IDEAL. Please deactivate the one with this acquirer account: **iDealSimulatorAccount**

**Comment by ribeiroguilherme** [comment]
@JordiDekker if the issue persists, please reach out to support! Cheers

**Comment by JordiDekker** [comment]
Issue was resolved by enabling iDEAL 2.0 by the Adyen support. Thanks!
