### ISSUE TITLE
"Could not get Apple Pay session" error in logs

### ISSUE THREAD

**Issue by willhowlett** [Adyen/adyen-web#2888]
Hi, we have noticed a number of Apple Pay session errors in our logs. They seem to be related to merchant validation. We get about 50 errors a day (so very low numbers but something we want to address). We have been in touch with Adyen support but felt it would be worth raising an issue here as it does not seem to be configuration related.
 
We use the Adyen Apple Pay certificate and the Apple Pay component (not dropin). We use @adyen/adyen-web version 5.52.0 and 5.55.1 (2 different environments, with the error happening for both versions)
 
The errors we receive are
 
`Could not get Apple Pay session`
`InvalidAccessError: The object does not support the operation or argument.`

<img width="611" alt="Screenshot 2024-10-03 at 10 53 27" src="https://github.com/user-attachments/assets/2a4917af-073b-47b4-8ca6-81c9781b3d2e">

This is thrown when calling `completeMerchantValidation` inside the `onvalidatemerchant` method of ApplePayService.ts
https://github.com/Adyen/adyen-web/blob/f574a64bacefc9ffced49beb012654faad029e41/packages/lib/src/components/ApplePay/ApplePayService.ts#L75

The only related issue I’ve found online is this https://stackoverflow.com/a/39480875, which makes me wonder if maybe there are scenarios where what is passed to `completeMerchantValidation` is inaccurate. I'm drawn to the `You can use the merchant session object a single time` line on https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/providing_merchant_validation and am wondering if there could be scenarios (rerenders perhaps) where the same session data is used twice

We are using a fairly standard implementation using the example [here](https://github.com/adyen-examples/adyen-react-online-payments/blob/main/src/features/payment/Payment.js) as a base. We log when our component remounts and don't see that happening (so if a rerender is causing a stale merchant session object I don't think the rerender is happening on our application)

Is this an error that anyone has seen before or has any idea about the possible cause of? Many thanks

**Comment by ribeiroguilherme** [comment]
Hey @willhowlett ,

Do you have any visibility of what happens when this error occurs? Does the ApplePay payment sheet closes and shopper needs to retry/try another payment method or is it still possible to make the payment? Are you by any chance catching any error in the `onError` callback? It is quite hard to tell what could be going wrong here

---

> The only related issue I’ve found online is this https://stackoverflow.com/a/39480875, which makes me wonder if maybe there are scenarios where what is passed to completeMerchantValidation is inaccurate. I'm drawn to the You can use the merchant session object a single time line on https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/providing_merchant_validation and am wondering if there could be scenarios (rerenders perhaps) where the same session data is used twice

The session is created every time that the button is pressed, so it must be a different session every time the button is clicked. We do not keep it saved anywhere in order to reuse it, so I believe this use-case of reusing the same session twice is possible.

---

Regarding your implementation and the example that you used as base, I'd tweak it a bit since the ApplePay has the `isAvailable()` method which detects if you should mount or not the Component within the page:

```js
const applepay = checkout.create('applepay');

applepay.isAvailable()
  .then(() => {
    applepay.mount('#applepay-container');
  })
  .catch(() => {
   // Component not available
  });
```

**Comment by ribeiroguilherme** [comment]
One thing that you could possibly do in order to check what is being passed to the `completeMerchantValidation` and to verify that this is not being triggered 'multiple times' due to some re-render is to provide your own `onValidateMerchant` function to the ApplePay Component.

As part of its implementation, you can write your code following [what we have in place](https://github.com/Adyen/adyen-web/blob/v5/packages/lib/src/components/ApplePay/ApplePay.tsx#L110). This way you will be able to always verify the response of the session data and also be able to have more ownership of what is being passed to `completeMerchantValidation` function.  Perhaps this can help to spot the issue.

**Comment by willhowlett** [comment]
Many thanks for the response! Regarding `isAvailable` we do already do an ApplePaySession check higher up the stack to decide whether to include ApplePay at all, however we're going to modify it to match the `isAvailable` check [here](https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/ApplePay/ApplePay.tsx#L281) so will see if that makes any difference

We'll have a look at implementing our own `onValidateMerchant` method as well.

Thanks again for the advice. I will post back if we see any results

**Comment by ribeiroguilherme** [comment]
@willhowlett nice! I hope it works for you. I am going to close this issue for now, but feel free to reach out back again if the problem persists after your changes. We can reopen this thread and follow up on the problem.

Cheers

**Comment by willhowlett** [comment]
Hiya. Just wanted to report back that matching the Adyen isAvailable check seems to have made a difference (we have had 5  `Could not get Apple Pay session` in the last week which look to just be network issues)

The `InvalidAccessError: The object does not support the operation or argument.` error looks to be occur when the user closes the pay sheet before the validation occurs (video attached) so not a biggie. User here reports the same thing: https://forums.developer.apple.com/forums/thread/740453

Just thought I'd let you know in case it comes up again for other users

Thanks for your time!

https://github.com/user-attachments/assets/ae69d069-3de3-4e0b-ba9b-586e00ab8067
