### ISSUE TITLE
GooglePay native payment sheet not working in newer version of Adyen Web script

### ISSUE THREAD

**Issue by jureperak** [Adyen/adyen-web#2943]
**Describe the bug**
Google Pay Native Payment Sheet is not functioning as expected in the latest version of your web script (at the moment 6.5.0). It shows the "web-view" instead of the native window. 
We are using Adyen Web Components/Drop-in v6.5.0 with dropin approach.

We know that your example shop, https://www.mystoredemo.io/# uses Adyen-web version 6.5.0

But we if rollback to the version e.g. 5.64.0 it will open GooglePay with Android native payment sheet.

We have tried with version 6.0.3. and also didn't work. So we assume that something was changed in major release 6.0.0

**To Reproduce**
1. Go to https://www.mystoredemo.io/#
2. Add product to cart
3. Go to cart
4. Select Google Pay as the payment method.
5. Click the "Pay with Google Pay" button.
6. It will open Android web-view window

**Expected behavior**
Should open Android native payment sheet

**Screenshots**
Native example how it should be:
![native](https://github.com/user-attachments/assets/c088ef97-5365-4c51-b1c9-e0276a73041f)
web-view example how it is now
![web-view](https://github.com/user-attachments/assets/b3321ade-e6b6-4f7d-9c3b-041aa7cbc7f7)

**Smartphone (please complete the following information):**
 - Device: Galaxy S22 SM-S901B/DS
 - OS: Android 14
 - Browser: Google Chrome
 - Browser version: 130.0.6723.102

**Comment by dmengelt** [comment]
@jureperak both screens are native 😉

We are currently working on migrating everything to the more modern bottom sheet (your first image). The reason why you started seeing the older native screen (your second image) is because Adyen started to use Google Pay `callbackIntents`. We are currently sending traffic involving callbacks (offers, shipping, dynamic price updates) to the older native screen.

The migration for all Google Pay traffic to show the new native screen should complete still this year.

Sorry for the inconvenience...

**Comment by ribeiroguilherme** [comment]
Thanks for following up on this @dmengelt .

I am closing this issue since there is nothing we can do from the adyen-web side. Hopefully this improvement lands soon to everyone 🙏 

Cheers
