### ISSUE TITLE
webdropIn PayPal Button is shown with showPayButton : false configuration in since version 3.7.0

### ISSUE THREAD

**Issue by AlexanderSeel** [Adyen/adyen-web#341]
**Describe the bug**
We used version 3.6.3 and in configuration showPayButton : false, because we use our own button.
When we try to update to a version above 3.6.3 it shows always at the paypal payment the "PayPal" button and payment with our own button, results in js exception.

**To Reproduce**
 Use Version webdrop above 3.6.3
set const configuration = {{
            showPayButton:false,

**Expected behavior**
Hide the paypal button and process payment like in version 3.6.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by pabloai** [comment]
Hi @AlexanderSeel, and thanks for reaching out.

The PayPal flow cannot be fire triggered by calling some method (as discussed in paypal/paypal-checkout-components#522) I'm not sure how useful it could be to hide the button completely.

This was working before because it was a completely different integration which relied in a redirection instead of opening the PayPal pop up.

Could you describe you use case? Would you use the PayPal component in some other part of the page?
Cheers!

**Comment by pabloai** [comment]
Hi @AlexanderSeel,
We've added this in version 3.16.0. Please have in consideration what I mention in the message above.

Feel free to reach out if you have more questions or ideas, cheers!

**Comment by AlexanderSeel** [comment]
Hi, 

sorry for the late response.
We integrated the flow with redirect, so with our own button we trigger the payment in the web dropin, send the response to our backend call your c# lib method, take the response and give it back to the web drop in.
The question is: Is this still possible with paypal or not?
Kind regards
