### ISSUE TITLE
onSelect not being called

### ISSUE THREAD

**Issue by bitbytebit1** [Adyen/adyen-web#973]
**Describe the bug**
After updating to 4.2.1 onSelect is no longer being called when changing payment methods

**To Reproduce**

**Expected behavior**
onSelect should be called when changing payment methods

**Screenshots**
When inspecting the adyen dropin props we can see that all of the callback events are correctly being set except onReady, onSelect, onComplete

![image](https://user-images.githubusercontent.com/11243425/115022404-a178fb00-9ebd-11eb-8f74-37f3acd8c7e0.png)

**Comment by marcperez** [comment]
Hi @bitbytebit1,

Thanks for reaching. This was one of the braking changes of v4.0.0: https://docs.adyen.com/online-payments/migrate-to-web-4-0-0#dropin-configuration

The `onSelect` and `onReady` events, since they're not generic events, should be defined when creating the Drop-in component, for example:

```js
const dropin = checkout.create('dropin', {
  onSelect: () => { /* ... */ },
  onReady: () => { /* ... */ }
});
```

Hope this helps!

**Comment by bitbytebit1** [comment]
Wicked, thanks for the information!
