### ISSUE TITLE
Global events from AdyenCheckout are not emitted 

### ISSUE THREAD

**Issue by emidev98** [Adyen/adyen-web#992]
Dear Adyen Frontend Team,
When I updated the library from version **4.2.3** to **4.3.0** I have noticed that the next configuration is not emitting the global events anymore:

```TypeScript
const checkout = new AdyenCheckout({
    onSubmit: () => {}, // Global configuration for onSubmit
    onReady: () => {},
    onSelect: () => {},
    onChange: () => {},
    onSubmit: () => {},
    onError: () => {},
    onAdditionalDetails: () => {}
});
 
checkout.create('dropin').mount('#dropin');
```

Then I had to do this workaround:
```TypeScript
const checkout = new AdyenCheckout();
 
checkout.create('dropin',{
    onSubmit: () => {}, // Global configuration for onSubmit
    onReady: () => {},
    onSelect: () => {},
    onChange: () => {},
    onSubmit: () => {},
    onError: () => {},
    onAdditionalDetails: () => {}
}).mount('#dropin');
```

**Additional context**
We have seen that there were some props changed [from the **main** config to the **create** function](https://docs.adyen.com/online-payments/drop-in-web#configuring-drop-in). 
Is it on propose that the events are not emitted anymore in **AdyenCheckout** but yes on **checkout.create()** or it was a bug?

Thanks,
Emilian

**Comment by bitbytebit1** [comment]
Hello, I had the same issue a few days ago, see [here](https://github.com/Adyen/adyen-web/issues/973)

**Comment by emidev98** [comment]
Thanks, I have didn't seen the ticket as was closed.
Cheers🍺  @bitbytebit1

**Comment by marcperez** [comment]
Hi @emidev98,

Happy to see this was clarified already (thanks @bitbytebit1!). Since we noticed this confusion popped up a couple times, we just added a link to the [migration guide to v4](https://docs.adyen.com/online-payments/migrate-to-web-4-0-0) in our [release notes](https://docs.adyen.com/online-payments/release-notes) which hopefully will help others in the future with this issue. Thanks for reaching!
